name: C/C++ CI

on:
  push:
    branches: ["main"]
    tags:
      - "v*"

  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: make build

      - name: Prepare release files
        run: |
          mkdir release
          cp libguilib.a release/
          cp include/gui.h release/

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/libguilib.a
            release/gui.h
